In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import healpy as hp
import cv2
from scipy.sparse import dok_matrix
import os
import math
import time
import traceback
from scipy import sparse, spatial
from pygsp import utils
from pygsp.graphs import Graph
from pygsp.graphs.nngraphs.spherehealpix import SphereHealpix

In [9]:
def calNpix(NSIDE = 512):
    print(
        "Approximate resolution at NSIDE {} is {:.2} deg".format(
            NSIDE, hp.nside2resol(NSIDE, arcmin=True) / 60))
    NPIX = hp.nside2npix(NSIDE)
    print (NPIX)
    ipix = np.arange(NPIX)
    return ipix, NPIX

In [3]:
def sphericalToSphereMapCoords(phi,theta, imgWidth, imgHeight):
    KPi2Inverted=0.002777778
    KPiInverted = 0.005555556
    x=imgWidth * (1. - (theta * KPi2Inverted)) - .5
    y=(imgHeight * phi) * KPiInverted - .5
    x=np.round(x)
    y=np.round(y)
    x=x.astype(int)
    y=y.astype(int)
    return x,y

In [36]:
def sampleImage(path,x,y):
    i=1
    for filename in os.listdir(path):
        if filename.endswith(".jpg") or filename.endswith(".png"):
            img=cv2.imread(filename)
            img=cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            #print (array)
            #print (img.shape)
            #print (y,x)
            #print (img[y,x])
            array=img[y,x]
            np.save(str(i),array)
            i=i+1

In [37]:
def main():
    NSIDE=512
    ipix, NPIX=calNpix(NSIDE)
    #Getting the values of phi and theta for all the pixels
    phi, theta = np.degrees(hp.pix2ang(nside=NSIDE, ipix=ipix)) #where phi is between 0 and 180, theta is 
                                                          #between 0 and 360   
    subdivisions = int(math.sqrt(NPIX / 12))
    #G = SphereHealpix(subdivisions, nest=True, k=20)
    x,y=sphericalToSphereMapCoords(phi,theta,3535,1768)
    sampleImage('.',x,y)

In [38]:
main()

Approximate resolution at NSIDE 512 is 0.11 deg
3145728
(1768, 3535, 3)
[   0    0    0 ... 1767 1767 1767] [3093 2209 1325 ... 2209 1325  441]
[[102  86  73]
 [102  86  73]
 [101  85  72]
 ...
 [189 138  85]
 [184 137  85]
 [187 140  88]]
(1768, 3535, 3)
[   0    0    0 ... 1767 1767 1767] [3093 2209 1325 ... 2209 1325  441]
[[100  86  75]
 [100  86  73]
 [105  88  78]
 ...
 [187 141  82]
 [182 136  84]
 [179 133  83]]
(1768, 3535, 3)
[   0    0    0 ... 1767 1767 1767] [3093 2209 1325 ... 2209 1325  441]
[[100  84  71]
 [101  85  72]
 [100  82  70]
 ...
 [200 157 115]
 [200 155 114]
 [199 156 113]]


In [25]:
img=cv2.imread('00000001.jpg')
img[1390,2]

array([ 83, 142, 192], dtype=uint8)

In [ ]:
#code adapted from https://math.stackexchange.com/questions/243142/what-is-the-general-formula-for-calculating-dot-and-cross-products-in-spherical
phi_sin=np.sin(phi)
phi_cos=np.cos(phi)
theta_sin=np.sin(theta)
theta_cos=np.cos(theta)
x=[0]
start = time.time()
#x=np.arange(1000)                 # Made a trial run for 1000 pixels but we should loop it over 786287 pixels (ipix)
for i in ipix:
    vector_product=((phi_sin[i]*phi_sin*(theta_cos[i]*theta_cos+theta_sin[i]*theta_sin)+phi_cos[i]*phi_cos)>0.9996) 
    #0.99998 is a hyper parameter based on the number of neighbours we want
    index=np.nonzero(vector_product)
    X_i =
    S[i, index] = 1
    
end =time.time()
print (end-start)

In [ ]:
csr_matrix=S.tocsr() 